### ISSUE TITLE
App needs a better name!

### ISSUE THREAD

**Issue by ybakos** [ybakos/crcp3320-scoreboard#1]

**Comment by dallen93** [comment]
Does the new name have to be relatively close to the old name?

**Comment by ybakos** [comment]
@dallen93 Nope.

Need this for issue #2.

**Comment by ybakos** [comment]
Gamazonian.
Scoralicious.
Points.
WhoDaBest.

**Comment by klr27** [comment]
ScoreMaster

**Comment by psaajc1420** [comment]
@klr27 simple but elegant.I like it
All I have is ScoreMachine and Scorzilla haha

**Comment by abejosua** [comment]
Score-Tab or Game Chronicles.
I like @klr27 's . haha

**Comment by bradquill** [comment]
@klr27 ScoreMaster is really good
Score Center
So you think you can Score?

**Comment by ybakos** [comment]
ScoreMeister?

**Comment by alexhibb** [comment]
Can I get yo Number?
Score War

**Comment by alexhibb** [comment]
Numbers Never Lie

- this used to be a name of a tv show.......

**Comment by blwatkins** [comment]
Who Got Game?

King of the App

I like @klr27 ScoreMaster. I also like @alexhibb Score War. If you change it to Score Wars, it can be a kind of play on words (Score Wars, Star Wars).

**Comment by ybakos** [comment]
@blwatkins "Score (Star) Wars" brings some easy design ideas to mind.
I like Who Got Game?.

**Comment by ybakos** [comment]
The winner per in-class discussion on Nov 6:

# Score Wars
