### ISSUE TITLE
Need "new game" html mockup

### ISSUE THREAD

**Issue by ybakos** [ybakos/crcp3320-scoreboard#7]
Game name
game icon

**Comment by blwatkins** [comment]
I was looking at the screen specification, and I noticed that we put in an option to edit games, but there is no specific "edit game" screen.  Should the "new game" be used for game addition and game editing, or will we be adding a separate screen for each?

**Comment by ybakos** [comment]
That's right - I combined both "new" and "edit" into one screen. Note the blue asterisks in the screen spec. For now, just create the "new game" screen. We'll later repurpose this to be used for both, dynamically. (Same goes for all new/edit screens.)

**Comment by blwatkins** [comment]
Thank you, @ybakos
